name: Universal CI Pipeline

on:
  push:
    branches: [ "main", "master", "dev" ]  # Rodar nestas branches
  pull_request:
    branches: [ "main", "master", "dev" ]  # Rodar em PRs

jobs:
  detect-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect language and run appropriate commands
        run: |
          echo "🔍 Detecting project type..."
          
          # ====================
          # 1. Node.js (JavaScript/TypeScript)
          # ====================
          if [[ -f "package.json" ]]; then
            echo "📦 Node.js project detected"
            npm install
            npm run build --if-present
            npm test --if-present
          fi

          # ====================
          # 2. Python
          # ====================
          if [[ -f "requirements.txt" ]]; then
            echo "🐍 Python project detected"
            pip install -r requirements.txt
            python -m pytest || true
          fi

          # ====================
          # 3. Java (Maven)
          # ====================
          if [[ -f "pom.xml" ]]; then
            echo "☕ Java project detected"
            mvn clean install
          fi

          # ====================
          # 4. Go
          # ====================
          if [[ -f "go.mod" ]]; then
            echo "🐹 Go project detected"
            go test ./...
          fi

          # ====================
          # 5. Ruby
          # ====================
          if [[ -f "Gemfile" ]]; then
            echo "💎 Ruby project detected"
            bundle install
            bundle exec rspec || true
          fi

          # ====================
          # 6. PHP
          # ====================
          if [[ -f "composer.json" ]]; then
            echo "🐘 PHP project detected"
            composer install
            ./vendor/bin/phpunit || true
          fi

          # ====================
          # 7. C/C++ (Make)
          # ====================
          if [[ -f "Makefile" ]]; then
            echo "🛠️  C/C++ project detected"
            make
          fi

          # ====================
          # 8. Docker
          # ====================
          if [[ -f "Dockerfile" ]]; then
            echo "🐳 Docker project detected"
            docker build -t my-app .
          fi
